version: 2

models:
  - name: stg_lobelia4cosmetics
    description: "Staging model for raw lobelia4cosmetics Telegram messages. Cleans and standardizes raw data for downstream modeling."
    columns:
      - name: staging_id
        description: "Surrogate key for the staging table."
        tests:
          - unique
          - not_null
      - name: message_id
        description: "Original message ID from Telegram."
        tests:
          - not_null
      - name: message_date
        description: "Timestamp of the message."
        tests:
          - not_null
      - name: text
        description: "Text content of the message."
      - name: image_path
        description: "Path to the image file, if present."
      - name: raw_json
        description: "Original raw JSON payload."

  - name: stg_tikvahpharma
    description: "Staging model for raw tikvahpharma Telegram messages. Cleans and standardizes raw data for downstream modeling."
    columns:
      - name: staging_id
        description: "Surrogate key for the staging table."
        tests:
          - unique
          - not_null
      - name: message_id
        description: "Original message ID from Telegram."
        tests:
          - not_null
      - name: message_date
        description: "Timestamp of the message."
        tests:
          - not_null
      - name: text
        description: "Text content of the message."
      - name: image_path
        description: "Path to the image file, if present."
      - name: raw_json
        description: "Original raw JSON payload."

  - name: dim_channels
    description: "Dimension table for Telegram channels. Provides a unique list of channels with surrogate keys."
    columns:
      - name: channel_id
        description: "Surrogate key for the channel."
        tests:
          - unique
          - not_null
      - name: channel_name
        description: "Name of the Telegram channel."
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Date dimension table for time-based analysis."
    columns:
      - name: date_id
        description: "Surrogate key for the date."
        tests:
          - unique
          - not_null
      - name: date
        description: "Calendar date."
        tests:
          - unique
          - not_null
      - name: year
        description: "Year component of the date."
      - name: month
        description: "Month component of the date."
      - name: day
        description: "Day component of the date."
      - name: weekday
        description: "Day of week (0=Sunday, 6=Saturday)."

  - name: fct_messages
    description: "Fact table for Telegram messages, joined to channel and date dimensions. Includes message length and image presence."
    columns:
      - name: message_id
        description: "Original message ID from Telegram."
        tests:
          - not_null
      - name: channel_id
        description: "Foreign key to dim_channels."
        tests:
          - not_null
      - name: date_id
        description: "Foreign key to dim_dates."
        tests:
          - not_null
      - name: message_length
        description: "Length of the message text."
      - name: has_image
        description: "Boolean flag indicating if the message has an image."
      - name: message_date
        description: "Timestamp of the message."
      - name: raw_json
        description: "Original raw JSON payload."
    tests:
      - dbt_utils.expression_is_true:
          expression: "message_length > 0"
          name: "message_length_positive"
          config:
            severity: warn
            tags: [custom, quality] 